# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


def add_some_dressings(apps, schema_editor):
    Dressing = apps.get_model('dressings', 'Dressing')
    for dressing in ['Vinaigrette', 'Ranch', 'Thousand Island']:
        Dressing.objects.create(name=dressing)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dressing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(add_some_dressings)
    ]
