name: testing

on:
  push:
    branches: master
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test tools
        run: |
          sudo apt-get update
          sudo apt-get install gettext

          pip install tox-travis
          pip install coverage

      - name: Execute tests
        run: |
          tox

          coverage report -m
